# Generated by Django 4.2.23 on 2025-07-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('excerpt', models.TextField()),
                ('author', models.CharField(default='Admin', max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.TextField()),
                ('status', models.CharField(default='draft', max_length=15)),
                ('link', models.TextField()),
            ],
        ),
    ]
